apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-app
spec:
  selector:
    matchLabels:
      app: secret-app
  template:
    metadata:
      labels:
        app: secret-app
    spec:
      securityContext:
        fsGroup: 2000
      containers:
        - name: app-container
          image: denny/go-demo-app:v1
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
