apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-app
spec:
  selector:
    matchLabels:
      app: resource-app
  template:
    metadata:
      labels:
        app: resource-app
    spec:
      containers:
        - name: app-container
          image: denny/go-demo-app:v1
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
